# Generated by Django 4.1.7 on 2023-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
