# Generated by Django 4.1.7 on 2023-03-19 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='jobuploaddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
