# Generated by Django 4.1.7 on 2023-03-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobpost_jobuploaddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='jobuploaddate',
        ),
        migrations.AddField(
            model_name='profile',
            name='foundername',
            field=models.TextField(blank=True),
        ),
    ]
