# Generated by Django 4.1.7 on 2023-03-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_jobpost_jobuploaddate_profile_foundername'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='founderage',
            field=models.TextField(blank=True),
        ),
    ]
