# Generated by Django 4.1.7 on 2023-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equity',
            field=models.TextField(blank=True),
        ),
    ]
