# Generated by Django 4.1.7 on 2023-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cin_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='incorporation_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='patents_published',
            field=models.TextField(blank=True),
        ),
    ]
