# Generated by Django 4.2 on 2023-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_cin_no_profile_incorporation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='jobcompany',
            field=models.TextField(default='My Company', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='jobexperience',
            field=models.CharField(choices=[('belowtwo', '0 to 2 years'), ('twotofive', '2 to 5 years'), ('fivetoten', '5 to 10 years'), ('aboveten', 'Above 10 years')], default='0 to 2 years', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='jobmode',
            field=models.CharField(choices=[('office', 'Work From Office'), ('remote', 'Work From Home'), ('hybrid', 'Hybrid')], default='Work From Office', max_length=20),
        ),
    ]
