# Generated by Django 4.2 on 2023-05-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_jobpost_jobcompany_alter_jobpost_jobexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='jobdepartment',
            field=models.TextField(default='Engineering', max_length=240),
        ),
    ]
