# Generated by Django 4.2 on 2023-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_jobpost_jobdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagramurl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='startupname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtubeurl',
            field=models.TextField(blank=True),
        ),
    ]
