# Generated by Django 4.2 on 2023-05-28 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profile_department_profile_instagramurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startuppost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('startupname', models.TextField()),
                ('startupsector', models.TextField()),
                ('startupbio', models.TextField()),
                ('startuplocation', models.TextField()),
                ('startupestablishment', models.TextField()),
                ('startupcin', models.TextField()),
                ('startupincorporation', models.TextField()),
                ('startuppatents', models.TextField()),
                ('startupwebsite', models.TextField()),
                ('startuplinkedin', models.TextField()),
                ('startupinstagram', models.TextField()),
                ('startupyoutube', models.TextField()),
                ('startupfoundername', models.TextField()),
                ('startupfounderage', models.TextField()),
                ('startupfoundereducation', models.TextField()),
                ('startupfounderexperience', models.TextField()),
                ('startupfounderequity', models.TextField()),
                ('startupfocusarea', models.TextField()),
                ('startupservices', models.TextField()),
            ],
        ),
    ]
