# Generated by Django 4.2 on 2023-05-28 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_startuppost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startuppost',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False),
        ),
    ]
